### ISSUE TITLE
identica has no uid set

### ISSUE THREAD

**Issue by dominikh** [omniauth/omniauth#104]
When using the identica strategy, uid is empty after logging in:

```
--- 
provider: identica
uid: 
credentials: 
  token: ...
  secret: ...
extra: 
  access_token: !ruby/object:OAuth::AccessToken 
    consumer: !ruby/object:OAuth::Consumer 
```

(token and secret have been replaced by me.)
