### ISSUE TITLE
[Question]: in-memory testing database experience?

### ISSUE THREAD

**Issue by txapelgorri** [omniauth/omniauth#805]
I'm testing an in-memory test environment. This is my config/database.yml:

```
test:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 10000
  #database: db/test.sqlite3
  database: ":memory:"
```

schema.rb is loaded when running rspec, but the test fails and complains: "ActiveRecord::StatementInvalid: Could not find table 'authorizations'"

If the test DB is not in memory but as a regular file, then it works fine. Is this an issue or just a particular environment wrong configuration?.
