### ISSUE TITLE
Access to collection of configured providers

### ISSUE THREAD

**Issue by jasonkarns** [omniauth/omniauth#891]
Feature Request/Help

I'm trying to create a log-in page that iterates through all providers and creates the appropriate button for each one. I see that OmniAuth.strategies is a nice collection of the strategies, however it only stores the class for each strategy. I can't find anywhere in OmniAuth where the strategies are instantiated such that I can grab the `request_path`.

Suggestions?

**Comment by andrewshadura** [comment]
I solved this by adding another initialiser:
```ruby
path = Rails.root.join("config", "auth.yml")

begin
    CONFIG['sso_auth'] = YAML.load_file(path)
rescue Exception
    puts "Error while parsing config file #{path}"
    CONFIG['sso_auth'] = Hash.new
end

Rails.application.config.middleware.use OmniAuth::Builder do
    CONFIG['sso_auth'].each do |name, options|
        options[:name] = name
        provider (options['strategy'] || name), options
    end
end
```
and then configuring authentication strategies in a YAML file instead:
```yaml
indieauth:
  client_id: https://website.project.org/
project-gitlab:
  strategy: gitlab
  description: Project GitLab
  scope: read_user openid profile email
  client_id: hexhexhexhex
  client_secret: hexhexhexhex
  client_options:
    site: https://gitlab.project.org/api/v4
```
